In [1]:
# Installing yellowbrick
!pip install yellowbrick

Requirement already satisfied: yellowbrick in ./.conda/lib/python3.10/site-packages (1.5)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.2 in ./.conda/lib/python3.10/site-packages (from yellowbrick) (3.10.0)
Requirement already satisfied: scipy>=1.0.0 in ./.conda/lib/python3.10/site-packages (from yellowbrick) (1.15.3)
Requirement already satisfied: scikit-learn>=1.0.0 in ./.conda/lib/python3.10/site-packages (from yellowbrick) (1.7.2)
Requirement already satisfied: numpy>=1.16.0 in ./.conda/lib/python3.10/site-packages (from yellowbrick) (2.2.6)
Requirement already satisfied: cycler>=0.10.0 in ./.conda/lib/python3.10/site-packages (from yellowbrick) (0.12.1)
Requirement already satisfied: contourpy>=1.0.1 in ./.conda/lib/python3.10/site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (1.3.2)
Requirement already satisfied: fonttools>=4.22.0 in ./.conda/lib/python3.10/site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.conda/lib/python3.10/site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (1.5.0)
Requirement already satisfied: packaging>=20.0 in ./.conda/lib/python3.10/site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (26.2)
Requirement already satisfied: pillow>=8 in ./.conda/lib/python3.10/site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (12.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in ./.conda/lib/python3.10/site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in ./.conda/lib/python3.10/site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.conda/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib!=3.0.0,>=2.0.2->yellowbrick) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in ./.conda/lib/python3.10/site-packages (from scikit-learn>=1.0.0->yellowbrick) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in ./.conda/lib/python3.10/site-packages (from scikit-learn>=1.0.0->yellowbrick) (3.6.0)

In [2]:
pip install -U scikit-learn

Requirement already satisfied: scikit-learn in ./.conda/lib/python3.10/site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in ./.conda/lib/python3.10/site-packages (from scikit-learn) (2.2.6)
Requirement already satisfied: scipy>=1.8.0 in ./.conda/lib/python3.10/site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in ./.conda/lib/python3.10/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in ./.conda/lib/python3.10/site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
# install the package needed by the extension
%pip install nb-black

Collecting nb-black
  Using cached nb_black-1.0.7.tar.gz (4.8 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in nb_black setup command: 'install_requires' must be a string or iterable of strings containing valid project/version requirement specifiers; Expected semicolon (after name with no version specifier) or end
          yapf >= '0.28'; python_version < '3.6'
               ^
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed to build 'nb-black' when getting requirements to build wheel
Note: you may need to restart the kernel to use updated packages.

In [4]:
import warnings

warnings.filterwarnings("ignore")


# Libraries to help with reading and manipulating data
import numpy as np
import pandas as pd

# to perform PCA
from sklearn.decomposition import PCA

# Libraries to help with data visualization
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme()

# Removes the limit for the number of displayed columns
pd.set_option("display.max_columns", None)
# Sets the limit for the number of displayed rows
pd.set_option("display.max_rows", 200)

# to scale the data using z-score
from sklearn.preprocessing import StandardScaler

# to compute distances
from scipy.spatial.distance import cdist

# to perform k-means clustering and compute silhouette scores
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# to visualize the elbow curve and silhouette scores
from yellowbrick.cluster import KElbowVisualizer, SilhouetteVisualizer

In [5]:
#Loading dataset
student_Registration = pd.read_csv("studentRegistration.csv")

In [6]:
student_Registration.shape

(32593, 5)

In [7]:
student_Registration.head()

,code_module,code_presentation,id_student,date_registration,date_unregistration
0,AAA,2013J,11391,-159.0,NaN
1,AAA,2013J,28400,-53.0,NaN
2,AAA,2013J,30268,-92.0,12.0
3,AAA,2013J,31604,-52.0,NaN
4,AAA,2013J,32885,-176.0,NaN

In [8]:
student_Registration.tail()

,code_module,code_presentation,id_student,date_registration,date_unregistration
32588,GGG,2014J,2640965,-4.0,NaN
32589,GGG,2014J,2645731,-23.0,NaN
32590,GGG,2014J,2648187,-129.0,NaN
32591,GGG,2014J,2679821,-49.0,101.0
32592,GGG,2014J,2684003,-28.0,NaN

In [9]:
student_Registration.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   code_module          32593 non-null  object
 1   code_presentation    32593 non-null  object
 2   id_student           32593 non-null  int64
 3   date_registration    32548 non-null  float64
 4   date_unregistration  10072 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 1.2+ MB

In [10]:
student_Registration.isnull().sum()

code_module                0
code_presentation          0
id_student                 0
date_registration         45
date_unregistration    22521
dtype: int64

In [11]:
student_Registration.describe().T

,count,mean,std,min,25%,50%,75%,max
id_student,32593.0,706687.669131,549167.313855,3733.0,508573.0,590310.0,644453.0,2716795.0
date_registration,32548.0,-69.411300,49.260522,-322.0,-100.0,-57.0,-29.0,167.0
date_unregistration,10072.0,49.757645,82.460890,-365.0,-2.0,27.0,109.0,444.0

In [12]:
student_Registration.fillna(0)

,code_module,code_presentation,id_student,date_registration,date_unregistration
0,AAA,2013J,11391,-159.0,0.0
1,AAA,2013J,28400,-53.0,0.0
2,AAA,2013J,30268,-92.0,12.0
3,AAA,2013J,31604,-52.0,0.0
4,AAA,2013J,32885,-176.0,0.0
...,...,...,...,...,...
32588,GGG,2014J,2640965,-4.0,0.0
32589,GGG,2014J,2645731,-23.0,0.0
32590,GGG,2014J,2648187,-129.0,0.0
32591,GGG,2014J,2679821,-49.0,101.0
32592,GGG,2014J,2684003,-28.0,0.0

In [13]:
 #create unique identifier for course run
student_Registration["code_module_presentation"]=student_Registration[['code_module','code_presentation']].agg('-'.join,axis=1)
student_Registration.head()

,code_module,code_presentation,id_student,date_registration,date_unregistration,code_module_presentation
0,AAA,2013J,11391,-159.0,NaN,AAA-2013J
1,AAA,2013J,28400,-53.0,NaN,AAA-2013J
2,AAA,2013J,30268,-92.0,12.0,AAA-2013J
3,AAA,2013J,31604,-52.0,NaN,AAA-2013J
4,AAA,2013J,32885,-176.0,NaN,AAA-2013J

In [14]:
student_Registration.nunique()

code_module                     7
code_presentation               4
id_student                  28785
date_registration             332
date_unregistration           416
code_module_presentation       22
dtype: int64

In [15]:
#Merging student_Registration data set.
 #create unique identifier for course run
student_Registration["code_module_presentation"]=student_Registration[['code_module','code_presentation']].agg('-'.join,axis=1)
student_Registration.head()

,code_module,code_presentation,id_student,date_registration,date_unregistration,code_module_presentation
0,AAA,2013J,11391,-159.0,NaN,AAA-2013J
1,AAA,2013J,28400,-53.0,NaN,AAA-2013J
2,AAA,2013J,30268,-92.0,12.0,AAA-2013J
3,AAA,2013J,31604,-52.0,NaN,AAA-2013J
4,AAA,2013J,32885,-176.0,NaN,AAA-2013J

In [16]:
# create unique identifier for each student in the course run

student_Registration= student_Registration.astype({'id_student':'string'})
student_Registration["code_module_student_presentation"]=student_Registration[['code_module_presentation','id_student']].agg('-'.join,axis=1)
student_Registration.head()

,code_module,code_presentation,id_student,date_registration,date_unregistration,code_module_presentation,code_module_student_presentation
0,AAA,2013J,11391,-159.0,NaN,AAA-2013J,AAA-2013J-11391
1,AAA,2013J,28400,-53.0,NaN,AAA-2013J,AAA-2013J-28400
2,AAA,2013J,30268,-92.0,12.0,AAA-2013J,AAA-2013J-30268
3,AAA,2013J,31604,-52.0,NaN,AAA-2013J,AAA-2013J-31604
4,AAA,2013J,32885,-176.0,NaN,AAA-2013J,AAA-2013J-32885

In [17]:
student_Registration = student_Registration.drop(columns=['code_module','code_presentation','id_student'])
student_Registration.head()

,date_registration,date_unregistration,code_module_presentation,code_module_student_presentation
0,-159.0,NaN,AAA-2013J,AAA-2013J-11391
1,-53.0,NaN,AAA-2013J,AAA-2013J-28400
2,-92.0,12.0,AAA-2013J,AAA-2013J-30268
3,-52.0,NaN,AAA-2013J,AAA-2013J-31604
4,-176.0,NaN,AAA-2013J,AAA-2013J-32885

#Date_Registration and date_unregistraion features are importent for 25% Early drop out analysis

In [18]:
for col in student_Registration.select_dtypes(include=['object']).columns:
    student_Registration[col] = student_Registration[col].str.strip().str.lower()

In [19]:
for col in student_Registration.select_dtypes(include=['object','float','int']).columns:
    print(col)
    print(student_Registration[col].unique())
    print("_" * 40)

date_registration
[-159.  -53.  -92.  -52. -176. -110.  -67.  -29.  -33. -179. -103.  -47.
  -59.  -68. -180.  -95. -130.  -50. -107.  -27.  -31. -170.  -62. -100.
 -109.    5.  -43.  -26.  -32.  -99.  -82. -197.  -75.  -96. -195.  -61.
  -37.  -36. -132. -138. -174.  -44.  -16.  -54.  -64.  -46. -117.  -45.
 -162.  -57.  -39. -128.  -74.  -12. -136.  -73.  -51. -169. -172. -108.
 -165.  -58.  -79.    2. -151. -198. -186. -145. -191.  -17.   -8. -141.
  -80. -115.  -83.  -18.  -66. -123. -121. -192. -196.   48.  -71.  -81.
  -60.  -49.  -38. -129.   -4.  -19.  -87. -155. -185.  -23.  -15. -120.
 -156. -127.  -30. -158.  -22.  -91.  -42. -144.  -63.  -35.   20. -102.
 -124. -106. -164. -137.  -65. -148. -113. -116.  -28.  -85.  -56. -101.
  -24.  -94.  -11. -105. -153.  -48.  -25.  -72.  -78.  -41. -150. -143.
 -149. -154.  -89.    3.  -21. -135.  -20.   -5. -134.  -10. -122.  -88.
 -147. -114.  -84.  -14.  -70. -140.  -93. -119.   -7.  -86. -146.   10.
  -55. -111. -227. -131. -255.  -97. -104. -166.  -34.  -90.  -77.   -9.
 -256. -233. -193. -260. -266.    6. -276.   -6. -221. -173. -118. -210.
   69. -182. -142. -157.  -76. -161. -126. -171. -208.   -2. -133.  -98.
    9.   -1.   16.   nan -225.   11.   -3. -211. -248. -253. -112. -219.
 -235. -231. -194.   23. -178. -163. -184. -183. -125.   27. -177. -190.
 -167.    4.   32.    1. -139. -236.   81.   59. -269. -309. -289. -321.
 -168. -279.  -69. -284. -229. -320. -200. -261.   21. -322. -207. -215.
 -268. -258. -222. -270. -264. -188. -232. -217. -175.   14.   12. -160.
   17.   44.   13. -257. -243. -201.  -40. -234. -311. -244. -213. -241.
 -187. -310. -152. -305. -218. -204. -226. -304. -246. -262. -303. -277.
 -220. -199. -285. -286. -242. -240. -247. -205. -295. -251. -290. -281.
 -299. -297. -263. -298. -273. -209. -291. -214. -181. -228. -206. -202.
  -13. -302. -282. -267. -254. -312. -274.   37.   19. -237. -280. -245.
 -238. -272.   49.  124.  167. -216. -283. -203.  101.   24. -189.   82.
 -249. -239. -275.   83.    0.   28.   40.   18.  110.]
________________________________________
date_unregistration
[  nan   12.   96.   72.  175.  135.   30.  144.  129.   58.  158.  191.
  123.   60.  185.  166.  109.  170.  187.  177. -121.   -3.   53.   65.
  160.   51.    5.  202. -100.  172.  119.   73.  128.  241.   23.  173.
  203.   27.   37.  103.   -2.  240.  138.  163.   10.  178.  -19.  -50.
  -80.  242.  220.  114.  219.   13.  199.   93.   39.  164.  235.  207.
  143.   24.  234.  104.  201.   67.  -87.  229.  132. -101.  -47.  165.
  227.   18.  174. -137.  -12.   80.  -22.  150.  -11. -129.    9.  228.
  180.  182.  213.   63.   32.  108.  110.   34.   55.  146.  -16.  -54.
   38.  226.   -8.  153.  139.   59.   86.  -75.   42.   -4.  -59. -225.
  157.   68.   11.   76.   33.   25.    6.  -68.   -9.  -65.  -25.  -92.
   -1.   -5.  208.   95.   48.  -82.  198.   22. -117.   54. -163.   57.
   47.   81.  200.  136.   83.   61.  -18.  137.  102.  -36.  152.  100.
  -73.  130.  -30.  121.  145.   66. -209.  195. -109.   31.  156. -106.
  -29.   87.   26.  -26.  159.  216.  116.  212.  209.  223.  188.   44.
   89.   82.   40.   46.  118.   74.  -96.   49.    3.    4.  -81.   69.
  167.   20.   16.  -23. -142.   79.   29. -131.   14.  -28.   62.   90.
  -17.  113.  125.  -94.  148.   97.  101.   45.   88.  -45.  149.    2.
  122.  222.  -49.  183.   17.  -15.  184.  -85.   28.  -44.  179.   99.
  124.  115.  206.    0.  142.  186.  154.  168.  111.   56.  215. -136.
  -43.  217.  -53.  105.  -51.  236.  -32.  -61.  -14.  -67.  117.  -52.
 -176.  -57.  -84.  112.  192.  -33.  -71.  -78.  -42.  -72.  -86.  -21.
  -46.  171.  214.  107.  -37.  221.  -95. -110.  237.  140.  -93.  -58.
  -64.   85. -123.  -24.   19. -124. -178. -103. -138. -107. -114.  -91.
 -113.  -38. -108.   84.   70.   35.  -10.  -56.  131.   94.  189.  194.
   41.  -31.  224.  -20. -120. -143.   -7.   75. -171.  -88.  169.   15.
 -126.  -27. -141. -212.  -60. -317. -128. -118. -177.  -77.  151. -122.
  -41.  205.  -89.   98.  -97.  -79.  127.    7. -149.   92.  197.  147.
  -39.  193. -155.   52.   -6.    1. -152.  -40. -156.  -74.   78. -102.
  230.  190.  -66.  133.    8.  134. -204.  161. -148.  126.   50.  106.
 -169. -232.  -99. -133.   21. -262.  -98.  225.   64. -185. -205. -179.
 -194. -197.  162.  -63. -158. -168. -145. -105.  204. -206.  141.  211.
   71. -130.   43.  239.   77.  196.  155.  233.  210.  -35.  -48.  218.
 -191. -116. -271. -184.  181.  232.  120. -166.   36. -196. -144.  231.
 -192. -274. -248. -147. -213.  176.   91. -134. -115. -119. -207. -220.
 -127. -157. -140.  444.  -62. -297. -365. -112. -151.]
________________________________________
code_module_presentation
['aaa-2013j' 'aaa-2014j' 'bbb-2013b' 'bbb-2013j' 'bbb-2014b' 'bbb-2014j'
 'ccc-2014b' 'ccc-2014j' 'ddd-2013b' 'ddd-2013j' 'ddd-2014b' 'ddd-2014j'
 'eee-2013j' 'eee-2014b' 'eee-2014j' 'fff-2013b' 'fff-2013j' 'fff-2014b'
 'fff-2014j' 'ggg-2013j' 'ggg-2014b' 'ggg-2014j']
________________________________________
code_module_student_presentation
['aaa-2013j-11391' 'aaa-2013j-28400' 'aaa-2013j-30268' ...
 'ggg-2014j-2648187' 'ggg-2014j-2679821' 'ggg-2014j-2684003']
________________________________________

In [20]:
student_Registration.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32588    False
32589    False
32590    False
32591    False
32592    False
Length: 32593, dtype: bool

In [21]:
student_Registration.duplicated().any()

np.False_

In [22]:
student_Registration[student_Registration.duplicated(keep=False)]

Empty DataFrame
Columns: [date_registration, date_unregistration, code_module_presentation, code_module_student_presentation]
Index: []

### There is no duplicated values in entire dataset

# Next step : will go for univariate and bivariate analysis for categorical and int type data